# Generated by Django 5.0.7 on 2024-07-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modersite", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="preferencesuser",
            name="email_notifications",
            field=models.BooleanField(
                db_index=True,
                default=False,
                verbose_name="Receive notifications by email",
            ),
        ),
    ]
